# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate config on push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.XLUI_GITHUB }}
        SSH_EMAIL: ${{ secrets.XLUI_EMAIL }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "$SSH_EMAIL"
        git config --global user.name "xlui"

    - name: Generate AD list
      run: |
        cd factory
        python ad.py
        python build_confs.py
        cd ..

    - name: Commit
      run: |
        git add .
        git commit -m "Auto-update on push"
